"""empty message

Revision ID: 0044b121b516
Revises: 
Create Date: 2026-03-16 14:40:51.745414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0044b121b516'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credential_info', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roles_and_responsibilities', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('examination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('board_university', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objective_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objective_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('professional_summary_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('professional_summary_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technical_summary_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technical_summary_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technology_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themeconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('font_family', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_font_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('light_bg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('light_accent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('light_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('light_card_bg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dark_bg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dark_accent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dark_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dark_card_bg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('themeconfig')
    op.drop_table('skill')
    op.drop_table('project')
    op.drop_table('profile')
    op.drop_table('education')
    op.drop_table('company')
    op.drop_table('certification')
    # ### end Alembic commands ###
