"""Add gmail_url to profile

Revision ID: e4724018053e
Revises: 0044b121b516
Create Date: 2026-03-17 12:53:22.259990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4724018053e'
down_revision: Union[str, Sequence[str], None] = '0044b121b516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'profile',
        sa.Column(
            'gmail_url',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'gmail_url')
    # ### end Alembic commands ###
